Oleksii ozyrskyi your order
NatalinaMatioshko/7-Days-To-Deadline pull request #1
Opened 2024-05-24 20:59 UTC by lexxus0

просто дивлюсь як то працює :)

2024-05-25 11:39 UTC, NatalinaMatioshko requested changes
потрібно дещо пофіксити

2024-05-25 11:39 UTC, NatalinaMatioshko commented on src/partials/section-order.html
> +  <h2 class="title-in-your-order visually-hidden">Your order</h2>
тут поставте id="your-order"

2024-05-25 11:39 UTC, NatalinaMatioshko commented on src/partials/section-order.html
> +          /img/your-order/desktop-pic-for-form@2x.jpg 2x
тут стоїть десктоп замість таблет

2024-05-25 11:39 UTC, NatalinaMatioshko commented on src/css/section-order.css
> +  padding-top: 40px;
цей паддінг не потрібен, у вас вже стоїть марджин боттом 80 під картинкою

2024-05-26 12:07 UTC, NatalinaMatioshko requested changes

2024-05-26 12:07 UTC, NatalinaMatioshko commented on src/partials/section-order.html
> +  <div class="green-picture-container"></div>
цей дів також потрібно видалити

2024-05-26 14:37 UTC, lexxus0 commented
Gotovo.

2024-05-26 17:10 UTC, NatalinaMatioshko approved these changes

2024-05-26 17:10 UTC, merged