Studennij collection
NatalinaMatioshko/7-Days-To-Deadline pull request #4
Opened 2024-05-25 12:43 UTC by CrockFrey

Input + CSS

2024-05-25 14:16 UTC, NatalinaMatioshko requested changes
підгружайте картинки

2024-05-26 09:18 UTC, CrockFrey commented
Картинки підгрузив, все решта готово.

2024-05-26 10:30 UTC, CrockFrey commented
Деякі зміни по орнаменту

2024-05-26 14:49 UTC, NatalinaMatioshko approved these changes

2024-05-26 14:49 UTC, merged